---
title: "employment.html"
---

<h1 style="padding-top:10px;">Employment History</h1>

<hr/>

## Utah Department of Health and Human Services, Salt Lake City, Utah

<p style="font-size:14px;font-weight: bold;color:black;padding:0px;">Senior Health Informaticist, Office of Informatics and Data Systems, (2021 - Present)</p>

In this role I have served as R Shiny application developer, health informaticist, and project manager.

* Developed and maintained internal dashboards for tracking and analyzing community health and epidemiology data in support of the State DHHS COVID-19 response. Platforms used include both R Shiny and DOMO. Focus on producing robust, production-grade R Shiny applications including code documentation and automated testing.

* Other duties include working with MySQL and PostgreSQL databases via these dashboard applications as well as configuring Mirth as a health data transfer tool between databases and other data sources.

* As project manager successfully initiated a current project to implement replacement/improvement of the case management application system for the Office of the Medical Examiner and Chief Medical Examiner. Shepherded OME staff through request for proposal process in search of software vendor, provider selection and project kickoff. Currently managing this project.

## Stantec Consulting Inc. (formerly MWH Americas, Inc.), Salt Lake City, Utah

<p style="font-size:14px;font-weight: bold;color:black;padding:0px;">Associate - Environmental Scientist (2005 - 2021)</p>

In this role I have served in technical and managerial capacity completing environmental projects for federal agencies and private industry. Duties have included:

* Project Scientist/Analyst
* Supervisor
* Project Manager
* Client Service Manager


<p style="font-size:14px;font-weight: bold;color:black;padding:0px;">Technical Leader - Environmental Services Data Analysis and Statistics, United States (2016-2021)</p>
  
In this role I have served to promote consistent data management and analysis practices within my company, and served as a proponent of repeatable and transparent analysis practices, including training colleagues and producing data products with R Shiny and R Markdown, among other platforms.

* Technical Lead - Data Analysis and Statistics

* Technical Lead - Digital Practice
  
<hr/>
  
## Applied Biosciences, Salt Lake City, Utah
  
  <p style="font-size:14px;font-weight: bold;color:black;padding:0px;">Research Scientist/Field Technician (2003-2005)</p>
  
I served as microbiologist and bench-scale research scientist, as well as field technician to design and construct full scale bioreactors for the treatment of arsenic and selenium in mining wastewaters.
 
<hr/> 
  
## USDA Forest Service, Stanley, Idaho
  
  <p style="font-size:14px;font-weight: bold;color:black;padding:0px;">Field Scientist/Developer, Sawtooth Wilderness Inventory and Monitoring Program (2000-2002)</p>

Along with another biologist, I developed and implemented a multi-disciplinary inventory and monitoring system for the Sawtooth Wilderness in Idaho, USA. The program included surveys and data management system development to support long-term monitoring of endangered species, user impacts, water quality and vegetation conditions within the Sawtooth Wilderness, a program that is still going strong today.
  
  
  
  
  




